<template><div><h2 id="_4-1-事件机制" tabindex="-1"><a class="header-anchor" href="#_4-1-事件机制"><span>4.1 事件机制</span></a></h2>
<p>​		众所周知，页面在加载时，会触发<code v-pre>Load</code>事件。当用户单击某个按钮时，触发该按钮的<code v-pre>Click</code> 事件，通过种种事件实现各项功能或执行某项操作。事件在元素对象与功能代码中起着重要的桥梁作用。那么，事件被触发后是如何执行代码的呢?严格来说，事件在触发后被分为两个阶段，一个是捕获(<code v-pre>Capture</code>)，另一个则是冒泡(<code v-pre>Bubbling</code>):</p>
<p>​		但有些遗憾的是，大多数浏览器并不是都支持捕获阶段，<code v-pre>jQuery</code>也不支持。因此在事件触发后，往往执行冒泡过程。所谓的冒泡其实质就是事件执行中的顺序。</p>
<p>​		下面通过示例 4-1来说明事件执行过程中的冒泡现象。</p>
<p>【示例 4-1】 事件中的冒泡现象</p>
<p>​		(1)功能描述</p>
<p>​		在页面中创建一个<code v-pre>&lt;div&gt;</code>标记，并在该标记中创建一个按钮。</p>
<p>​		当用户单击页面或者<code v-pre>&lt;div&gt;</code>标记或者按钮时，都在页面中显示一句问候语“您好，欢迎来到<code v-pre>jQuery</code>世界!”。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token function">$</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">var</span> intI<span class="token operator">=</span><span class="token number">0</span><span class="token punctuation">;</span><span class="token comment">//记录执行次数</span></span>
<span class="line">    <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">"body,div,#btnshow"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">click</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span><span class="token comment">//单击事件</span></span>
<span class="line">        intI<span class="token operator">++</span><span class="token punctuation">;</span><span class="token comment">//次数累加</span></span>
<span class="line">        <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">".clsShow"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">show</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token comment">//显示</span></span>
<span class="line">            <span class="token punctuation">.</span><span class="token function">html</span><span class="token punctuation">(</span><span class="token string">"您好，欢迎来到jQuery 世界!"</span><span class="token punctuation">)</span><span class="token comment">//设置内容</span></span>
<span class="line">            <span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token string">"&lt;div>执行次数&lt;b>"</span><span class="token operator">+</span> intI<span class="token operator">+</span><span class="token string">"&lt;/b>&lt;/div>"</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//追加文本</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>为什么在示例 4-1中，仅是单击按钮，但却执行了 3 次同样的程序呢?这是因为事件在执行过程中存在冒泡现象，即虽然单击的是按钮，但按钮的外围<code v-pre>&lt;div&gt;</code>元素的事件也被触发，同时<code v-pre>&lt;div&gt;</code>元素的外围<code v-pre>&lt;body&gt;</code>元素的事件也随之被触发，其整个事件波及的过程就像水泡一样向外冒，故称为冒泡过程。</p>
</blockquote>
<blockquote>
<p>而在实际需要中，我们并不希望事件的冒泡现象发生，即单击按钮就执行单一的单击事件，并不触发其他外围的事件。在<code v-pre>jQuery</code>中，可以通过<code v-pre>stopPropagation()</code>方法来实现，你会发现该方法可以阻止冒泡过程的发生。</p>
<p>我们将示例 4-1 中的<code v-pre>jQuery</code> 代码进行部分修改，如下所示</p>
</blockquote>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token function">$</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">var</span> intI<span class="token operator">=</span><span class="token number">0</span><span class="token punctuation">;</span><span class="token comment">//记录执行次数</span></span>
<span class="line">    <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">"body,div,#btnshow"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">click</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">event</span><span class="token punctuation">)</span><span class="token punctuation">{</span><span class="token comment">//单击事件</span></span>
<span class="line">        intI<span class="token operator">++</span><span class="token punctuation">;</span><span class="token comment">//次数累加</span></span>
<span class="line">        <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">".clsShow"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">show</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token comment">//显示</span></span>
<span class="line">            <span class="token punctuation">.</span><span class="token function">html</span><span class="token punctuation">(</span><span class="token string">"您好，欢迎来到jQuery 世界!"</span><span class="token punctuation">)</span><span class="token comment">//设置内容</span></span>
<span class="line">            <span class="token punctuation">.</span><span class="token function">append</span><span class="token punctuation">(</span><span class="token string">"&lt;div>执行次数&lt;b>"</span><span class="token operator">+</span> intI<span class="token operator">+</span><span class="token string">"&lt;/b>&lt;/div>"</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//追加文本</span></span>
<span class="line">        event<span class="token punctuation">.</span><span class="token function">stopPropagation</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 防止冒泡过程</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>​		修改完成后，执行示例 4-1，单击按钮后，其页面显示的执行次数为1，即仅是触发了按钮的单击事件，而没有波及其他外围元素事件。</p>
<blockquote>
<p>说明:</p>
<p>在代码中，除了使用 <code v-pre>stopPropagation()</code>方法阻止事件的冒泡过程外，还可以通过语句<code v-pre>return false</code> 实现停止事件的冒泡过程。</p>
</blockquote>
<h2 id="_4-2页面载入事件" tabindex="-1"><a class="header-anchor" href="#_4-2页面载入事件"><span>4.2页面载入事件</span></a></h2>
<h3 id="_4-2-1-ready-方法的工作原理" tabindex="-1"><a class="header-anchor" href="#_4-2-1-ready-方法的工作原理"><span>4.2.1 <code v-pre>ready()</code>方法的工作原理</span></a></h3>
<p>​		在前面的第 1 章节中，我们简单地介绍了<code v-pre>jQuery</code>中的页面载入事件<code v-pre>ready()</code>方法。该方法类似于传统 <code v-pre>JavaScript</code>中的 <code v-pre>OnLoad()</code>方法，只不过在事件执行时间上有区别:<code v-pre>OnLoad()</code>方法的执行必须是页面中的全部元素完全加载到浏览器后才触发，在这种情况下，如果页面中的图片过多或图片过大，那么有可能要等	<code v-pre>OnLoad()</code>	方法执行完毕，用户才能进行其他的操作;如果使用<code v-pre> jOuery</code> 中的 <code v-pre>ready()</code>方法加载页面，则只要页面的 <code v-pre>DOM</code> 模型加载完毕，就会触发 <code v-pre>ready()</code> 方法。因此，两者在事件的执行效果上<code v-pre>ready()</code>方法明显优于<code v-pre>JavaScript</code>中的 <code v-pre>OnLoad()</code>方法。</p>
<p>​		我们解剖一下<code v-pre>jQuery</code>中<code v-pre>ready()</code>方法的工作原理:在<code v-pre>jQuery</code>脚本加载到页面时，会设置一个<code v-pre>isReady</code>的标记，用于监听页面加载的进度，当然遇到执行<code v-pre>ready()</code>方法时，通过查看<code v-pre>isReady</code> 值是否被设置，如果未被设置，那么就说明页面并未加载完成，在此情况下，将未完成的部分用一个数组缓存起来，当全部加载完成后，再将未完成的部分通过缓存一一执行。</p>
<h3 id="_4-2-2-ready-方法的几种相同写法" tabindex="-1"><a class="header-anchor" href="#_4-2-2-ready-方法的几种相同写法"><span>4.2.2 ready()方法的几种相同写法</span></a></h3>
<p>以下几种代码写法其执行的效果是一样的。</p>
<p>写法一:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token function">$</span><span class="token punctuation">(</span>document<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">ready</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//代码部分7</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>写法二:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token function">$</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//代码部分</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>写法三:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token function">jQuery</span><span class="token punctuation">(</span>document<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">ready</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">	<span class="token comment">//代码部分</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>写法四:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token function">jQuery</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">//代码部分</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>其中写法二简洁明了，使用较为广泛。</p>
<h2 id="_4-3-绑定事件" tabindex="-1"><a class="header-anchor" href="#_4-3-绑定事件"><span>4.3 绑定事件</span></a></h2>
<p>我们在示例 4-1 中，使用如下的代码绑定按钮的单击事件:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token function">$</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">	<span class="token function">$</span><span class="token punctuation">(</span><span class="token string">"#btnshow"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">click</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">//执行代码</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>除了上述绑定事件的写法外，在<code v-pre>jQuery</code>中，还可以使用<code v-pre>bind()</code>方法进行事件的绑定。</p>
<p>下面对该方法进行详细的介绍。</p>
<p><code v-pre>bind()</code>功能是为每个选择元素的事件绑定处理函数，其语法格式如下:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token function">bind</span><span class="token punctuation">(</span>type<span class="token punctuation">,</span><span class="token punctuation">[</span>data<span class="token punctuation">]</span><span class="token punctuation">,</span>fn<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>其中参数<code v-pre>type</code>为一个或多个类型的字符串，如“<code v-pre>click</code>&quot;或“<code v-pre>change</code>”，也可以自定义类型;</p>
<p>可以被参数<code v-pre>type</code>调用的类型包括<code v-pre>blur</code>、<code v-pre>focus</code>、<code v-pre>load</code>、<code v-pre>resize</code>、<code v-pre>scroll</code>、<code v-pre>unload</code>、<code v-pre>click</code>、<code v-pre>dblclick</code>,<code v-pre>mousedown</code>、<code v-pre>mouseup</code>、<code v-pre>mousemove</code>、<code v-pre>mouseover</code>、<code v-pre>mouseout</code>、<code v-pre>mouseenter</code>、<code v-pre>mouseleave</code>,<code v-pre>change</code>、<code v-pre>select</code>、<code v-pre>submit</code>、<code v-pre>keydown</code>、<code v-pre>keypress</code>、<code v-pre>keyup</code>、 <code v-pre>error</code>。</p>
<p>参数 <code v-pre>data</code> 是作为<code v-pre>event.data</code> 属性值传递给事件对象的额外数据对象。</p>
<p>参数<code v-pre>fn</code> 是绑定到每个选择元素的事件中的处理函数。</p>
<p>下面通过两个例子来讲解绑定方法。</p>
<p>【示例 4-2】 用 bind 方法绑定事件</p>
<p>​		(1)功能描述</p>
<p>​		在页面中，设置一个按钮，通过<code v-pre>bind</code>方法给按钮绑定一个<code v-pre>click</code>事件，在该事件中，将自身的是否可用属性设置成<code v-pre>false</code>，即单击按钮后就不可使用。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token function">$</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">"#btnBind"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">bind</span><span class="token punctuation">(</span><span class="token string">"click"</span>，<span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token function">$</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">attr</span><span class="token punctuation">(</span><span class="token string">"disabled"</span>，<span class="token string">"disabled"</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//按钮不可用</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>【示例 4-3 】用映射方式绑定不同的事件</p>
<p>​		(1)功能描述</p>
<p>​		在页面中，设置一个文本框，通过映射的方式，给文本框绑定两个事件，一个是<code v-pre>focus</code>事件，另一个是<code v-pre>change</code> 事件。这两个事件执行时，均为显示事件的名称。</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token function">$</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">    <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">".txt"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">bind</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token function-variable function">focus</span><span class="token operator">:</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">"#divTiP"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">show</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token comment">//显示</span></span>
<span class="line">            <span class="token punctuation">.</span><span class="token function">html</span><span class="token punctuation">(</span><span class="token string">"执行的是focus事件"</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//设置文本</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">	<span class="token function-variable function">change</span><span class="token operator">:</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">"#divTiP"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">show</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token comment">//显示</span></span>
<span class="line">            <span class="token punctuation">.</span><span class="token function">html</span><span class="token punctuation">(</span><span class="token string">"执行的是change事件"</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//设置文本</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">   <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在方法 <code v-pre>bind</code> 中，第二个参数 <code v-pre>data</code>为可选项，表示作为<code v-pre>event.data</code>属性值传递到事件对象的额外数据对象，实际上，该参数很少使用，如果使用，那么可以通过该参数将一些附加的信息传递给事件处理函数中，在示例4-3中，将代码中的 <code v-pre>bind</code>方法修改成带 <code v-pre>data</code> 参数，其修改后的代码:</p>
<div class="language-javascript line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre v-pre><code><span class="line"><span class="token comment">//...省略头部代码由</span></span>
<span class="line"><span class="token function">$</span><span class="token punctuation">(</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">	<span class="token keyword">var</span> message<span class="token operator">=</span><span class="token string">"执行的是focus事件"</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">".txt"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">bind</span><span class="token punctuation">(</span><span class="token string">"focus"</span><span class="token punctuation">,</span><span class="token punctuation">(</span>msg<span class="token operator">:</span>message <span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">event</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">"#divTip"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">show</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token comment">//显示</span></span>
<span class="line">		<span class="token punctuation">.</span><span class="token function">html</span><span class="token punctuation">(</span>event<span class="token punctuation">.</span>data<span class="token punctuation">.</span>msg<span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//设置文本</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">:</span>message<span class="token operator">=</span><span class="token string">"执行的是change 事件"</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">'.txt'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">bind</span><span class="token punctuation">(</span><span class="token string">'change'</span><span class="token punctuation">,</span><span class="token punctuation">(</span>msg<span class="token operator">:</span>message <span class="token punctuation">}</span><span class="token punctuation">,</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">event</span><span class="token punctuation">)</span><span class="token punctuation">{</span></span>
<span class="line">        <span class="token function">$</span><span class="token punctuation">(</span>"#divTip<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">show</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token comment">//显示</span></span>
<span class="line">		<span class="token punctuation">.</span><span class="token function">html</span><span class="token punctuation">(</span>event<span class="token punctuation">.</span>data<span class="token punctuation">.</span>msg<span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//设置文本</span></span>
<span class="line">     <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token comment">//...省略主体代码</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_4-4-切换事件" tabindex="-1"><a class="header-anchor" href="#_4-4-切换事件"><span>4.4 切换事件</span></a></h2>
<p>在<code v-pre>jQuery</code>中，有两个方法用于事件的切换，一个是方法<code v-pre>hover()</code>，另一个是方法<code v-pre>toggle()</code>。</p>
<p>所谓切换事件，即有两个以上的事件绑定于一个元素，在元素的行为动作间进行切换。</p>
<p>如一个超级链接标记<code v-pre>&lt;a&gt;</code>，若想实现当鼠标悬停时触发一个事件，鼠标移出时又触发另一个事件，就可以调用<code v-pre>jQuery</code> 中的 <code v-pre>hover()</code>方法轻松实现。</p>
<h3 id="_4-4-1-hover-方法" tabindex="-1"><a class="header-anchor" href="#_4-4-1-hover-方法"><span>4.4.1 <code v-pre>hover()</code>方法</span></a></h3>
<p>调用<code v-pre>jQuery</code> 中的 <code v-pre>hover()</code>方法可以使元素在鼠标悬停与鼠标移出的事件中进行切换，该方法在实现运用中，也可以通过<code v-pre>jQuery</code>中的事件<code v-pre>mouseenter</code>与<code v-pre>mouseleave</code>进行替换。</p>
<p>下列代码是等价的。</p>
</div></template>


