<template><div><h1 id="简单过滤选择器" tabindex="-1"><a class="header-anchor" href="#简单过滤选择器"><span>简单过滤选择器</span></a></h1>
<p>过滤选择器根据某类过滤规则进行元素的匹配，书写时都以冒号(:)开头:简单过滤选择器是过滤选择器中使用最广泛的一种，其详细说明如表2-5所示。
表 2-5 简单过滤选择器语法</p>
<table>
<thead>
<tr>
<th>选择器</th>
<th>功能</th>
<th>返回值</th>
</tr>
</thead>
<tbody>
<tr>
<td>first()或:first</td>
<td>获取第一个元素</td>
<td>单个元素</td>
</tr>
<tr>
<td>last()或:last</td>
<td>获取最后一个元素</td>
<td>单个元素</td>
</tr>
<tr>
<td>:not(selector)</td>
<td>获取除给定选择器外的所有元素</td>
<td>元素集合</td>
</tr>
<tr>
<td>:even</td>
<td>获取所有索引值为偶数的元素，索引号从0开始</td>
<td>元素集合</td>
</tr>
<tr>
<td>:odd</td>
<td>获取所有索引值为奇数的元素，索引号从0开始</td>
<td>元素集合</td>
</tr>
<tr>
<td>:eq(index)</td>
<td>获取指定索引值的元素，索引号从0开始</td>
<td>单个元素</td>
</tr>
<tr>
<td>:gt(index)</td>
<td>获取所有大于给定索引值的元素，索引号从0开始</td>
<td>元素集合</td>
</tr>
<tr>
<td>:lt(index)</td>
<td>获取所有小于给定索引值的元素，索引号从0开始</td>
<td>元素集合</td>
</tr>
<tr>
<td>:header</td>
<td>获取所有标题类型的元素，如h1、h2……</td>
<td>元素集合</td>
</tr>
<tr>
<td>:animated</td>
<td>获取正在执行动画效果的元素</td>
<td>元素集合</td>
</tr>
</tbody>
</table>
</div></template>


